0.48.0: `mapSchema` option
smartprocure/mongo2crate pull request #13
Opened 2024-10-14 15:41 UTC by daveyarwood

Following our discussion last week, this adds a `mapSchema` option to allow preprocessing nodes (using `map` from `obj-walker`) in the input object before converting it to a Crate schema.

(I'm about to look at adding this same option to `mongo2elastic` as well.)

2024-10-14 16:56 UTC, daveyarwood commented
Per @dubiousdavid, I will add another change to this PR, making it so that overrides "chain" together and apply in sequence, instead of applying just the first override that is found for each path pattern.

2024-10-15 13:30 UTC, dubiousdavid requested changes

2024-10-15 13:30 UTC, dubiousdavid commented on src/convertSchema.test.ts
> +    it('can replace a leaf node', () => {
Let's remove all other tests related to the `mapSchema` option other than this one. We're just testing that `map` from `obj-walker` works with the tests, which isn't necessary.

2024-10-15 15:38 UTC, dubiousdavid approved these changes
Looks good.

2024-10-15 15:39 UTC, merged

2024-10-15 15:56 UTC, dshishkov commented on src/convertSchema.test.ts
> +    const result = convertSchema(schema, '"doc"."foobar"', {
I like the new behavior and the test explains it nicely